spring:
  application:
    name: booking-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booking?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    jdbc-url: jdbc:mysql://localhost:3306/booking?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: BookingHikariPool

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false
    contexts: dev
    drop-first: false
    default-schema: booking

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  # Cấu hình pattern cho console
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  # Cấu hình file log
#  file:
#    name: ./logs/application.log
#    max-size: 10MB
#    max-history: 30
#    total-size-cap: 1GB

  # Cấu hình level cho từng package
  level:
    root: INFO

    # Spring framework
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot: INFO

    # MyBatis
    com.tripto.booking_app.mapper: TRACE  # Log SQL với parameters
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG

    # Liquibase
    liquibase: INFO
    liquibase.changelog: DEBUG
    liquibase.executor: DEBUG
    liquibase.lockservice: DEBUG
    liquibase.database: DEBUG

    # Database
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    # Your application
    com.tripto.booking_app: DEBUG